## Exercice 1

In [146]:
import gymnasium as gym
import numpy as np


env = gym.make("FrozenLake-v1", is_slippery=True, render_mode=None)

print("Nombre d'états:", env.observation_space.n)
print("Nombre d'actions:", env.action_space.n)
    
for episode in range(10):
    state = env.reset()[0]
    done = False
    while not done:
        action = env.action_space.sample()  
        next_state, reward, done, _, _ = env.step(action)
        print(f"Épisode {episode}, État: {state}, Action: {action}, Récompense: {reward}")
        state = next_state

Nombre d'états: 16
Nombre d'actions: 4
Épisode 0, État: 0, Action: 3, Récompense: 0.0
Épisode 0, État: 0, Action: 3, Récompense: 0.0
Épisode 0, État: 1, Action: 1, Récompense: 0.0
Épisode 0, État: 0, Action: 0, Récompense: 0.0
Épisode 0, État: 0, Action: 1, Récompense: 0.0
Épisode 0, État: 0, Action: 2, Récompense: 0.0
Épisode 0, État: 1, Action: 2, Récompense: 0.0
Épisode 1, État: 0, Action: 1, Récompense: 0.0
Épisode 1, État: 1, Action: 2, Récompense: 0.0
Épisode 2, État: 0, Action: 2, Récompense: 0.0
Épisode 2, État: 1, Action: 0, Récompense: 0.0
Épisode 3, État: 0, Action: 2, Récompense: 0.0
Épisode 3, État: 0, Action: 3, Récompense: 0.0
Épisode 3, État: 0, Action: 2, Récompense: 0.0
Épisode 3, État: 0, Action: 2, Récompense: 0.0
Épisode 3, État: 4, Action: 1, Récompense: 0.0
Épisode 3, État: 8, Action: 3, Récompense: 0.0
Épisode 3, État: 8, Action: 2, Récompense: 0.0
Épisode 3, État: 9, Action: 2, Récompense: 0.0
Épisode 4, État: 0, Action: 2, Récompense: 0.0
Épisode 4, État: 1, A

## Exercice 2

In [121]:
# Initialisation de la Q-Table
num_states = env.observation_space.n
num_actions = env.action_space.n
q_table = np.zeros((num_states, num_actions))

# Affichage de la Q-Table initiale
print("Q-Table initialisée :")
print(q_table)

Q-Table initialisée :
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Exercice 3

In [156]:
# Définition des hyperparamètres
alpha = 0.1  # Taux d'apprentissage
gamma = 0.99  # Facteur de discount
epsilon = 0.8  # Exploration initiale
epsilon_decay = 0.995  # Décroissance d'epsilon
num_episodes = 5000  # Nombre d'épisodes

# Boucle d'apprentissage
for episode in range(num_episodes):
    state = env.reset()[0]
    done = False
    while not done:
        if np.random.rand() < epsilon:
            action = env.action_space.sample()  # Exploration
        else:
            action = np.argmax(q_table[state, :])  # Exploitation

        next_state, reward, done, _, _ = env.step(action)

        # Mise à jour de la Q-Table
        q_table[state, action] = q_table[state, action] + alpha * (reward + gamma * np.max(q_table[next_state, :]) - q_table[state, action])
        state = next_state
    
    epsilon *= epsilon_decay

print("Q-Table après entraînement :")
print(q_table)

Q-Table après entraînement :
[[0.55729164 0.47376851 0.4734743  0.47413035]
 [0.37069667 0.36107123 0.38652561 0.52033741]
 [0.42912087 0.41821641 0.41685385 0.4865086 ]
 [0.37878667 0.27255409 0.28749879 0.46985931]
 [0.56787016 0.46084579 0.37943137 0.32512516]
 [0.         0.         0.         0.        ]
 [0.39383036 0.13059572 0.15936234 0.13626658]
 [0.         0.         0.         0.        ]
 [0.37141834 0.44536859 0.49613478 0.61164197]
 [0.54014071 0.63066861 0.41832246 0.4953716 ]
 [0.65196212 0.36622726 0.37004223 0.37752476]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.42505831 0.59409454 0.71776553 0.56939427]
 [0.738243   0.81193027 0.73191411 0.73046906]
 [0.         0.         0.         0.        ]]


## Exercice 4

In [179]:
num_test_episodes = 100
successes = 0

for _ in range(num_test_episodes):
    state = env.reset()[0]
    done = False
    while not done:
        action = np.argmax(q_table[state, :]) 
        next_state, reward, done, _, _ = env.step(action)
        state = next_state
    
    if reward > 0:
        successes += 1

success_rate = successes / num_test_episodes
print(f"Taux de réussite de l'agent après apprentissage : {success_rate * 100:.2f}%")

Taux de réussite de l'agent après apprentissage : 89.00%
