# Exercice 1

In [2]:
import gymnasium as gym
import numpy as np

In [4]:
# Initialisation de l'environnement 
env = gym.make("Taxi-v3")

# Nombre d'etats et d'actions 
state_size = env.observation_space.n
action_size = env.action_space.n

In [6]:
# Création de la table de politique (policy_table)
policy_table = np.ones((state_size, action_size)) / action_size

# Création de la table de valeurs (value_table)
value_table = np.zeros(state_size)

# Affichage des premières lignes des tables
print("Premières lignes de policy_table:")
print(policy_table[:5])

print("\nPremières valeurs de value_table:")
print(value_table[:5])

Premières lignes de policy_table:
[[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
 [0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]]

Premières valeurs de value_table:
[0. 0. 0. 0. 0.]


# Exercice 2

In [16]:
# Nombre d'épisodes
num_episodes = 20

for episode in range(num_episodes):
    state, _ = env.reset()  # Réinitialisation de l'environnement
    done = False
    total_reward = 0
    steps = []

    while not done:
        action = env.action_space.sample()  # Sélection d'une action aléatoire
        next_state, reward, done, truncated, info = env.step(action)  # Exécution de l'action
        total_reward += reward
        steps.append((state, action, reward))
        state = next_state  # Mise à jour de l'état

    # Affichage des résultats de l'épisode
    print(f"Épisode {episode + 1}:")
    print(f"  Actions et récompenses: {steps}")
    print(f"  Récompense totale: {total_reward}\n")

# Fermeture de l'environnement
#env.close()

Épisode 1:
  Actions et récompenses: [(321, 5, -10), (321, 5, -10), (321, 3, -1), (321, 4, -10), (321, 0, -1), (421, 0, -1), (421, 3, -1), (421, 1, -1), (321, 2, -1), (341, 3, -1), (321, 1, -1), (221, 0, -1), (321, 1, -1), (221, 3, -1), (201, 5, -10), (201, 2, -1), (221, 1, -1), (121, 1, -1), (21, 4, -10), (21, 2, -1), (21, 5, -10), (21, 0, -1), (121, 2, -1), (121, 5, -10), (121, 5, -10), (121, 4, -10), (121, 1, -1), (21, 1, -1), (21, 5, -10), (21, 4, -10), (21, 5, -10), (21, 4, -10), (21, 0, -1), (121, 2, -1), (121, 0, -1), (221, 4, -10), (221, 3, -1), (201, 5, -10), (201, 4, -10), (201, 3, -1), (201, 3, -1), (201, 3, -1), (201, 3, -1), (201, 4, -10), (201, 1, -1), (101, 1, -1), (1, 3, -1), (1, 0, -1), (101, 5, -10), (101, 3, -1), (101, 1, -1), (1, 2, -1), (21, 4, -10), (21, 1, -1), (21, 2, -1), (21, 5, -10), (21, 5, -10), (21, 1, -1), (21, 3, -1), (1, 2, -1), (21, 1, -1), (21, 3, -1), (1, 0, -1), (101, 0, -1), (201, 3, -1), (201, 3, -1), (201, 1, -1), (101, 4, -10), (101, 3, -1), (10